name: Testing stuff

on:
  push:
    branches:
      - master
      - vime-dev
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages
        env:
          COMMIT_MESSAGES_JOINED: join( ${{ toJson(github.event.commits.*.message) }}, '' )
        run: echo "$COMMIT_MESSAGES_JOINED"